on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

defaults:
  run:
    working-directory: ./k6

jobs:
  k6_transpile_bundle_test:
    name: Transpile, bundle and run
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ 16, 18 ]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      - run: npm ci
      - run: npm run bundle
      - run: ls -la && cd dist && ls -la
      - name: Run local k6 test
        uses: grafana/k6-action@v0.2.0
        with:
          filename: k6/dist/get-200-status-test.js
